[package]
name = "website"
version = "0.1.0"
authors = ["sinvy <zhaixinyu@yandex.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.16.2"
wasm-bindgen = "0.2.63"
